/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Client = IDL.Record({
  'id' : IDL.Text,
  'taxId' : IDL.Text,
  'name' : IDL.Text,
  'contactPerson' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Time = IDL.Int;
export const InvoiceStatus = IDL.Variant({
  'paid' : IDL.Null,
  'sent' : IDL.Null,
  'overdue' : IDL.Null,
  'draft' : IDL.Null,
});
export const InvoiceLineItem = IDL.Record({
  'lineTotal' : IDL.Float64,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
  'medicineId' : IDL.Text,
});
export const Invoice = IDL.Record({
  'id' : IDL.Text,
  'issueDate' : Time,
  'status' : InvoiceStatus,
  'lineItems' : IDL.Vec(InvoiceLineItem),
  'clientId' : IDL.Text,
  'dueDate' : Time,
  'subTotal' : IDL.Float64,
  'totalAmount' : IDL.Float64,
  'taxAmount' : IDL.Float64,
  'taxRate' : IDL.Float64,
});
export const Medicine = IDL.Record({
  'id' : IDL.Text,
  'sku' : IDL.Text,
  'unitOfMeasure' : IDL.Text,
  'name' : IDL.Text,
  'category' : IDL.Text,
  'unitPrice' : IDL.Float64,
});
export const Payment = IDL.Record({
  'invoiceId' : IDL.Text,
  'notes' : IDL.Text,
  'paymentDate' : Time,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClient' : IDL.Func([Client], [], []),
  'createInvoice' : IDL.Func([Invoice], [], []),
  'createMedicine' : IDL.Func([Medicine], [], []),
  'deleteClient' : IDL.Func([IDL.Text], [], []),
  'deleteInvoice' : IDL.Func([IDL.Text], [], []),
  'deleteMedicine' : IDL.Func([IDL.Text], [], []),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAllMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClient' : IDL.Func([IDL.Text], [Client], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'overdueCount' : IDL.Nat,
          'totalRevenue' : IDL.Float64,
          'pendingAmount' : IDL.Float64,
          'paidCount' : IDL.Nat,
          'totalInvoices' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getInvoice' : IDL.Func([IDL.Text], [Invoice], ['query']),
  'getMedicine' : IDL.Func([IDL.Text], [Medicine], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordPayment' : IDL.Func([Payment], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedSampleData' : IDL.Func([], [], []),
  'updateClient' : IDL.Func([Client], [], []),
  'updateInvoice' : IDL.Func([Invoice], [], []),
  'updateInvoiceStatus' : IDL.Func([IDL.Text, InvoiceStatus], [], []),
  'updateMedicine' : IDL.Func([Medicine], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Client = IDL.Record({
    'id' : IDL.Text,
    'taxId' : IDL.Text,
    'name' : IDL.Text,
    'contactPerson' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Time = IDL.Int;
  const InvoiceStatus = IDL.Variant({
    'paid' : IDL.Null,
    'sent' : IDL.Null,
    'overdue' : IDL.Null,
    'draft' : IDL.Null,
  });
  const InvoiceLineItem = IDL.Record({
    'lineTotal' : IDL.Float64,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
    'medicineId' : IDL.Text,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Text,
    'issueDate' : Time,
    'status' : InvoiceStatus,
    'lineItems' : IDL.Vec(InvoiceLineItem),
    'clientId' : IDL.Text,
    'dueDate' : Time,
    'subTotal' : IDL.Float64,
    'totalAmount' : IDL.Float64,
    'taxAmount' : IDL.Float64,
    'taxRate' : IDL.Float64,
  });
  const Medicine = IDL.Record({
    'id' : IDL.Text,
    'sku' : IDL.Text,
    'unitOfMeasure' : IDL.Text,
    'name' : IDL.Text,
    'category' : IDL.Text,
    'unitPrice' : IDL.Float64,
  });
  const Payment = IDL.Record({
    'invoiceId' : IDL.Text,
    'notes' : IDL.Text,
    'paymentDate' : Time,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClient' : IDL.Func([Client], [], []),
    'createInvoice' : IDL.Func([Invoice], [], []),
    'createMedicine' : IDL.Func([Medicine], [], []),
    'deleteClient' : IDL.Func([IDL.Text], [], []),
    'deleteInvoice' : IDL.Func([IDL.Text], [], []),
    'deleteMedicine' : IDL.Func([IDL.Text], [], []),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAllMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClient' : IDL.Func([IDL.Text], [Client], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'overdueCount' : IDL.Nat,
            'totalRevenue' : IDL.Float64,
            'pendingAmount' : IDL.Float64,
            'paidCount' : IDL.Nat,
            'totalInvoices' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getInvoice' : IDL.Func([IDL.Text], [Invoice], ['query']),
    'getMedicine' : IDL.Func([IDL.Text], [Medicine], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordPayment' : IDL.Func([Payment], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedSampleData' : IDL.Func([], [], []),
    'updateClient' : IDL.Func([Client], [], []),
    'updateInvoice' : IDL.Func([Invoice], [], []),
    'updateInvoiceStatus' : IDL.Func([IDL.Text, InvoiceStatus], [], []),
    'updateMedicine' : IDL.Func([Medicine], [], []),
  });
};

export const init = ({ IDL }) => { return []; };