/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'id' : string,
  'taxId' : string,
  'name' : string,
  'contactPerson' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface Invoice {
  'id' : string,
  'issueDate' : Time,
  'status' : InvoiceStatus,
  'lineItems' : Array<InvoiceLineItem>,
  'clientId' : string,
  'dueDate' : Time,
  'subTotal' : number,
  'totalAmount' : number,
  'taxAmount' : number,
  'taxRate' : number,
}
export interface InvoiceLineItem {
  'lineTotal' : number,
  'quantity' : bigint,
  'unitPrice' : number,
  'medicineId' : string,
}
export type InvoiceStatus = { 'paid' : null } |
  { 'sent' : null } |
  { 'overdue' : null } |
  { 'draft' : null };
export interface Medicine {
  'id' : string,
  'sku' : string,
  'unitOfMeasure' : string,
  'name' : string,
  'category' : string,
  'unitPrice' : number,
}
export interface Payment {
  'invoiceId' : string,
  'notes' : string,
  'paymentDate' : Time,
  'amount' : number,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClient' : ActorMethod<[Client], undefined>,
  'createInvoice' : ActorMethod<[Invoice], undefined>,
  'createMedicine' : ActorMethod<[Medicine], undefined>,
  'deleteClient' : ActorMethod<[string], undefined>,
  'deleteInvoice' : ActorMethod<[string], undefined>,
  'deleteMedicine' : ActorMethod<[string], undefined>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllMedicines' : ActorMethod<[], Array<Medicine>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClient' : ActorMethod<[string], Client>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'overdueCount' : bigint,
      'totalRevenue' : number,
      'pendingAmount' : number,
      'paidCount' : bigint,
      'totalInvoices' : bigint,
    }
  >,
  'getInvoice' : ActorMethod<[string], Invoice>,
  'getMedicine' : ActorMethod<[string], Medicine>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordPayment' : ActorMethod<[Payment], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'updateClient' : ActorMethod<[Client], undefined>,
  'updateInvoice' : ActorMethod<[Invoice], undefined>,
  'updateInvoiceStatus' : ActorMethod<[string, InvoiceStatus], undefined>,
  'updateMedicine' : ActorMethod<[Medicine], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];